name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install brews
        run: brew install mono |
             brew install mono-libgdiplus

      - name: Build
        run: cd PKHeX.Mobile
             dotnet clean
             dotnet build
             dotnet build -c Release
