name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install homebrew 1
        run: brew install mono 

      - name: Install homebrew 2
        run: brew install mono-libgdiplus 

      - name: Install .NET SDK
        run: brew tap homebrew/cask-versions |
             brew install --cask dotnet-sdk
    
      - name: Build
        run: cd PKHeX.iOS |
             dotnet build
